#pragma once

#define CAPSWITCH_VERSION_MAJOR 1
#define CAPSWITCH_VERSION_MINOR 1
#define CAPSWITCH_VERSION_PATCH 0
#define CAPSWITCH_VERSION_BUILD 0
#define CAPSWITCH_VERSION_TUPLE 1,1,0,0
#define CAPSWITCH_VERSION_STRING "1.1.0"
#define CAPSWITCH_VERSION_WSTRING L"1.1.0"
