#pragma once

#define CAPSWITCH_VERSION_MAJOR 1
#define CAPSWITCH_VERSION_MINOR 2
#define CAPSWITCH_VERSION_PATCH 1
#define CAPSWITCH_VERSION_BUILD 0
#define CAPSWITCH_VERSION_TUPLE 1,2,1,0
#define CAPSWITCH_VERSION_STRING "1.2.1"
#define CAPSWITCH_VERSION_WSTRING L"1.2.1"
